name: Trigger EU FSF Worker

on:
  schedule:
    - cron: "0 2 * * *"   # every hour
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger worker repo
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          curl -s -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            https://api.github.com/repos/tnrtnch/eu_fsf_sanc/actions/workflows/scraper.yml/dispatches \
            -d '{"ref":"main"}'
